//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kunja.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gast
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public gast()
        {
            this.boeking = new HashSet<boeking>();
        }
    
        public int gastID { get; set; }
        public string voornaam { get; set; }
        public string achternaam { get; set; }
        public string adres { get; set; }
        public string woonplaats { get; set; }
        public string postcode { get; set; }
        public string telNr { get; set; }
        public string email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<boeking> boeking { get; set; }
    }
}
