//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kunja.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lodge
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public lodge()
        {
            this.reservering = new HashSet<reservering>();
        }
    
        public int lodgeID { get; set; }
        public int lodgeTypeID { get; set; }
        public string lodgeNaam { get; set; }
        public string lodgeNR { get; set; }
        public string bezettingsgraad { get; set; }
    
        public virtual lodgetype lodgetype { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reservering> reservering { get; set; }
    }
}
