//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kunja.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_A3D6D6_KunjaRensEntities1 : DbContext
    {
        public DB_A3D6D6_KunjaRensEntities1()
            : base("name=DB_A3D6D6_KunjaRensEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<boeking> boeking { get; set; }
        public virtual DbSet<gast> gast { get; set; }
        public virtual DbSet<lodge> lodge { get; set; }
        public virtual DbSet<lodgetype> lodgetype { get; set; }
        public virtual DbSet<reservering> reservering { get; set; }
    }
}
