//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kunja.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservering
    {
        public int reserveringID { get; set; }
        public int lodgeID { get; set; }
        public int boekingID { get; set; }
        public System.DateTime incheckDatum { get; set; }
        public System.DateTime uitcheckDatum { get; set; }
    
        public virtual boeking boeking { get; set; }
        public virtual lodge lodge { get; set; }
    }
}
